### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ady-yu** [Veronicium/Eider#1]
when running the command bash scripts/test_bert.sh eider test hoi, it occurs the following mistakes.
![image](https://user-images.githubusercontent.com/69707855/161211665-8275c1ac-abba-4a31-95e7-71eeefdf4991.png)
Besides, when running the command bash scripts/train_bert.sh eider test hoi, the best F1 only get 0.61158.
![image](https://user-images.githubusercontent.com/69707855/161212074-83b36c07-722b-4292-bb02-32e7d5f2fb10.png)

**Comment by Veronicium** [comment]
Hi, I tried to run the code on my computer and did not see that error. Are you using the complete DocRED dataset? The number of documents in the dev set should be 1000 instead of 998. I guess there's some inconsistency between the doc_id that leads to this error.

It's normal to get F1=61.15 after training. You'll likely see another performance gain after running test_bert.sh

**Comment by ady-yu** [comment]
> I see. The author of DocRED has updated dev.json after I downloaded it. Please check the original version of dev.json (with 1000 documents): https://drive.google.com/drive/folders/1owp7ZRbrMl_s1ljIh6AvnmniLJSliV6h?usp=sharing Thanks for raising this issue!
> 
> It's actually normal to get F1=61.15 after training. You'll likely see another performance gain after running test_bert.sh

Thanks you for you reply!!! I wonder what the command bash scripts/**test_bert.sh** eider test hoi occupy how much GPU memory. It seems 16G is not enough!

**Comment by Veronicium** [comment]
Can your set evi_eval_mode=none in test_bert.sh? The memory is 6571M in my computer after setting it.

**Comment by Veronicium** [comment]
> > I see. The author of DocRED has updated dev.json after I downloaded it. Please check the original version of dev.json (with 1000 documents): https://drive.google.com/drive/folders/1owp7ZRbrMl_s1ljIh6AvnmniLJSliV6h?usp=sharing Thanks for raising this issue!
> > It's actually normal to get F1=61.15 after training. You'll likely see another performance gain after running test_bert.sh
> 
> Thanks you for you reply!!! I wonder the command bash scripts/**test_bert.sh** eider test hoi occupy how much GPU memory. It seems 16G is not enough!


Can your set evi_eval_mode=none in test_bert.sh? The memory is 6571M in my computer after setting it.
