### ISSUE TITLE
How can i change the args to get test pred file?

### ISSUE THREAD

**Issue by WatsonWangZh** [Veronicium/Eider#2]

**Comment by cp3geek** [comment]
I have the same problem, have you solved it?i changed the evi_mode=test,and it occurs this problem
![QQ图片20220407212445](https://user-images.githubusercontent.com/43991815/162209365-310819e1-72c4-4725-afd6-dc496578859d.png)

**Comment by ZhichaoDuan** [comment]
> I have the same problem, have you solved it?i changed the evi_mode=test,and it occurs this problem ![QQ图片20220407212445](https://user-images.githubusercontent.com/43991815/162209365-310819e1-72c4-4725-afd6-dc496578859d.png)

Hi, I ran the experiments but only get around 61.2 F1 on bert-base, is there any specific params I should take care?
